### ISSUE TITLE
Upgrade reactor data model to fully support an arbitrarily-deep composite design pattern

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#1008]
Right now we have a sort-of hybrid [Composite design pattern](https://en.wikipedia.org/wiki/Composite_pattern) for the reactor data model, with the following players:

* ARMI's `ArmiObject` is the official pattern's `Component` (sorry, we have a naming conflict here)
* ARMI's `Composite` is the pattern's `Composite` (yay)
* ARMI's `Component` is the pattern's `Leaf` 

Things that could be improved:

* ARMI's `Leaf` class is the parent of `Component` and `Material`. This should be cleaned up so that there's just `Component` and it' only used for `Component`. (this is #1007)
* It should be possible to add `Component`s and `Composite`s to any parent `Composite` arbitrarily. 
   *  I have a branch going that tried allowing Components to have children but I've decided that this approach will be more sustainable/realistic. 
* `Assembly` and `Block` are special `Composites`. This is sort of ok but shouldn't be forced.

But for this ticket, let's just focus on the 2nd bullet: **Allow deeper nesting of components and composites within composites.**

This will support #477.

**Comment by john-science** [comment]
@drewj-usnctech Just FYI.

**Comment by john-science** [comment]
**Bump.** This is still super important.

Perhaps I need to pin this as High Priority for the next release.

**Comment by john-science** [comment]
And one year later... I still feel like this is really important for the over-all ARMI mission.

**Comment by yardasol** [comment]
@yardasol is intereted in this

**Comment by john-science** [comment]
This would be a GREAT improvement. And it'll have to happen at some point. 

But, be warned, this ticket will have tendrils all over the place. There are all kinds of functions that make assumptions about composites only have children that are components. It'll be a ton of little changes in ARMI, and more downstream.

I imagine the best solution here would be to first build a solid set of little tools to get the children of composites and so on. And then applying those, new, more general tools to solve all the little one-off problems you find.

**Comment by yardasol** [comment]
I've been looking thru the ARMI codebase (and older GH discussions/issues) most of the day and thinking about next steps.

From what I can glean from my reading:
1. Currently, a `Composite` object _can_ nest of other `Composite` objects via the `Composite._children` attribute. `Component` objects are also included in the `Composite._children` attribute, as they subclass `Composite`
    - `Composite.getChildren()` supports retrieval of child `Composite` objects up to a specified depth (or untel the end of the tree is reached)
    - `Composite.getComponents()` support retrieval of all `Component` objects present at the current tree level
1. `Component` objects technically have the `_children` attribute as well, but it is unused. The second bullet in "Phase 1" of [Discussion 960](https://github.com/terrapower/armi/discussions/960#discussioncomment-4415178) tasks that we should make `Component` subclass `ArmiObject` directly, which would avoid the possibility of a `Component` (the Composite design pattern's `Leaf`) from having any children.
    - #1449 is related to this, but for `ArmiObject` instead of `Component`
1. There has been a lot of good discussion about how the `Block` class is a bottleneck
    - [Discussion #503](https://github.com/terrapower/armi/discussions/503) details the desire to allow `Block` classes to contain other `Composite` objects and not just `Component` objects. Many old completed tasks are detailed there, but ones that are left to do appear to be
        - > What is a block, aside from a Composite with perhaps a bounding shape/hull? Axial heights within an Assembly are the first thing that comes to mind when thinking about the "weirdness" of a Block w.r.t. a more general Composite.
          - A design decision needs to be made and then documented, both in docpages and in docstring. 
        - > Transition block to use getChildren instead of getComponents
          - There is currently a mix of both? 
        - > Design specific stuff on Blocks and related should continually be funneled to more design- or physics-specific plugins as functions that take blocks as arguments.
        - > Allow components to be specified in input without a block
             - #504
        - > Clean up ArmiObject to not know about children.
          - #1449 
        - > See if a bunch of Component methods don't make sense directly on ArmiObject
        - >Think of better name for ArmiObject.
          - This is low priority, but ideas include: PartBase, PartGroup and Part for ArmiObject, Block/Composite, Component, or  ComponentBase, ComponentGroup, Component for the same.
 
1. From my conversations with @john-science and perusal of the code base, it seems the majority of the remaining work is getting the assumption of arbitrary `Composite` tree depth into any `Composite` related code (anything that handles an `Assembly` or `Block` (and potentially also any `Component`s, but I'd like to refactor `Component` to directly inherit `ArmiObject`)

1. All of these changes and concepts need to be propagated the ARMI input file and internally in the `Blueprint` machinery.

Some other miscellaneous items I found during my perusal, but don't fit into the "main" issue here:
1. Metaclass `Composite` and `Component`-subclass registration: both the `ArmiObject` and `Component` classes use a metaclass (`CompositeModelType` for `ArmiObject`, `ComponentType` for `Component`) to track subclasses. The former doesn't seem to be used anywhere in ARMI (or downstream) at all, while the latter does, but has the following note in it's docstring:
    ```python
     Warning
     -------
     The/ import-time metaclass-based component subclass registration was a good idea, but in practice
     has caused significant confusion and trouble. We will replace this soon with an explicit
     plugin-based component subclass registration system.
    ```
    So both of these systems should be removed at some point? **UPDATE**: The subclass registration is used in in database machinery, so this will be a larger effort than originally anticipated
2. #1134 and #1055 seem relevant
3. Also #540
4. Design concepts mentioned by @drewj-usnctech (@drewj-tp) in [Discussion 960](https://github.com/terrapower/armi/discussions/960#discussion-4546180)

**Comment by yardasol** [comment]
### Action Plan
- [x] 1. Remove children logic from `ArmiObject` 
  - #1449
- [ ] 2. Refactor `Component` to subclass `ArmiObject` directly
- [ ] 3. Redefine the scope and assumptions about the `Block` class
  - Related: #540 
- [ ] 4. Inject the assumption of arbitrary `Composite tree` depth into any `Composite` related code (anything that handles an `Assembly` or `Block`). Also find a betttter name/phrase for "`Composite` with children of `Composite`s"" (nested `Composite`s?)
- [ ] 5. Make sure we have a diagram of this structure in the docs explaining what each thing does
Later:
- [ ] Change syntax of `iterComponents` to `iterChildren`
- [ ] #1134
- [ ] #1055

**Comment by john-science** [comment]
> Metaclass Composite and Component-subclass registration: both the ArmiObject and Component classes use a metaclass (CompositeModelType for ArmiObject, ComponentType for Component) to track subclasses. The former doesn't seem to be used anywhere in ARMI (or downstream) at all, while the latter does, but has the following note in it's docstring:

@yardasol If the metaclasses aren't useful to us, we can ditch them. No big deal. That should be it's own PR though.

And consider whether we want all of this in the docs  or just in the docstrings: https://terrapower.github.io/armi/developer/guide.html#the-reactor-data-model
